"""
Fallback parser for explicit commands.
"""
from typing import Optional

class FallbackParser:
    """
    Parser explicit command — digunakan saat AI tidak tersedia
    atau user menggunakan perintah ! secara langsung.
    """

    COMMAND_MAP = {
        "!screenshot": "screenshot",
        "!ss": "screenshot",
        "!video": "video",
        "!webcam": "webcam",
        "!webcamvid": "webcamvid",
        "!camvid": "webcamvid",
        "!sysinfo": "sysinfo",
        "!info": "sysinfo",
        "!ls": "list_files",
        "!cd": "cd",
        "!get": "get_file",
        "!lock": "lock_screen",
        "!lock_screen": "lock_screen",
        "!kunci": "lock_screen",
        "!unlock": "unlock",
        "!buka": "unlock",
        "!reboot": "reboot",
        "!term": "term",
        "!terminal": "term",
        "!exit": "exit",
        "!opencode": "opencode",
        "!agy": "agy",
        "!run": "run_script",
        "!testai": "testai",
        "!test-ai": "testai",
        "!help": "help",
        "!logout": "logout",
        "!clip": "clip",
        "!open": "open",
        "!top": "top",
        "!kill": "kill",
        "!volume": "volume",
        "!mute": "mute",
        "!brightness": "brightness",
        "!media": "media",
        "!battery": "battery",
        "!notif": "notif",
        "!process": "process",
        "!clipboard": "clip",
        "!alarm": "alarm",
        "!schedule": "schedule",
        "!listen": "listen",
        "!audio": "listen",
        "!active": "active",
        "!read": "clip",
        "!write": "clip",
        "!find": "find",
        "!search": "find",
        "!tts": "tts",
        "!ping": "ping",
        "!speedtest": "speedtest",
        "!win": "window_control",
        "!winctl": "window_control",
        "!web": "web",
        "!google": "web",
        "!scrape": "scrape",
        "!scrap": "scrape",
        "!scraper": "scrape",
        "!wifi": "wifi",
        "!ports": "ports",
        "!launch": "launch",
        "!todo": "todo",
        "!apps": "apps",
        "!guard": "guard",
        # PHASE 1: Core Productivity
        "!focus": "focus",
        "!pomodoro": "focus",
        "!workspace": "workspace",
        "!ws": "workspace",
        "!calendar": "calendar",
        "!cal": "calendar",
        "!quicknote": "quicknote",
        "!note": "quicknote",
        "!browser": "browser",
        "!chrome": "browser",
        "!daily": "daily",
        "!report": "daily",
        "!reminder": "reminder",
        "!remind": "reminder",
        "!task": "task",
        "!todoist": "task",
        "!meeting": "meeting",
        "!meet": "meeting",
        "!custom": "custom",
        "!alias": "custom",
        # PHASE 2: AI & Automation Intelligence
        "!ai": "ai",
        "!smart": "smart_clip",
        "!smartclip": "smart_clip",
        "!smart_clip": "smart_clip",
        "!macro": "macro",
        "!schedule": "schedule",
        "!jadwal": "schedule",
        "!voice": "voice_cmd",
        "!voicecmd": "voice_cmd",
        "!voice_cmd": "voice_cmd",
        "!suara": "voice_cmd",
        # PHASE 3: File, Sync & Data Management
        "!sync": "sync",
        "!upload": "quick_upload",
        "!quickupload": "quick_upload",
        "!quick_upload": "quick_upload",
        "!quick": "quick",
        "!recent": "recent",
        "!search": "search_content",
        "!searchcontent": "search_content",
        "!search_content": "search_content",
        "!cari": "search_content",
        "!convert": "convert",
        "!converter": "convert",
        "!backup": "backup",
        "!organize": "organize",
        "!rapikan": "organize",
        "!file": "file_watcher",
        "!watcher": "file_watcher",
        "!filewatcher": "file_watcher",
        "!version": "version",
        "!versi": "version",
        "!clean": "clean",
        "!bersihkan": "clean",
        "!pembersih": "clean",
        # PHASE 4: System Enhancement & Convenience
        "!power": "power",
        "!performance": "power",
        "!daya": "power",
        "!monitor": "multi_monitor",
        "!multimonitor": "multi_monitor",
        "!multi": "multi",
        "!display": "multi_monitor",
        "!sleep": "sleep",
        "!tidur": "sleep",
        "!wake": "wake",
        "!bangun": "wake",
        "!quickapp": "quick_app",
        "!night": "night_mode",
        "!nightmode": "night_mode",
        "!malam": "night_mode",
        "!window": "window",
        "!jendela": "window",
        "!hotkey": "hotkey",
        "!hotkeys": "hotkey",
        # New Input Actions
        "!key": "press",
        "!click": "click",
        "!type": "type",
        "!rightclick": "rightclick",
        "!clickkanan": "rightclick",
        "!doubleclick": "doubleclick",
        "!dobelklik": "doubleclick",
        "!drag": "drag",
        "!dragdrop": "drag",
        "!scroll": "scroll",
        "!gulir": "scroll",
        "!clickimage": "clickimage",
        "!clickimg": "clickimage",
        "!waitimage": "waitimage",
        "!waitimg": "waitimage",
        "!shell": "run",
        "!exec": "run",
        # PHASE 6: AI Advanced Intelligence
        "!memory": "memory",
        "!ingat": "memory",
        "!mcp": "mcp",
        "!companion": "companion",
        "!teman": "companion",
        "!solve": "solve",
        "!atasi": "solve",
        "!create": "create_feature",
        "!create_feature": "create_feature",
        "!buat": "create_feature",
        "!evolve": "self_evolve",
        "!self_evolve": "self_evolve",
        "!optimize": "optimize_me",
        "!optimize_me": "optimize_me",
        "!proactive": "proactive",
        "!proaktif": "proactive",
        "!learn": "learn",
        "!belajar": "learn",
        "!agent_mode": "agent_mode",
        # PHASE 7: Internet Omniscient
        "!internet_brain": "internet_brain",
        "!otak_internet": "internet_brain",
        "!live_web": "live_web",
        "!web_langsung": "live_web",
        "!deep_scrape": "deep_scrape",
        "!scrape_dalam": "deep_scrape",
        "!research": "research",
        "!riset": "research",
        "!verify_fact": "verify_fact",
        "!cek_fakta": "verify_fact",
        "!news_digest": "news_digest",
        "!ringkasan_berita": "news_digest",
        "!trend_hunter": "trend_hunter",
        "!pemburu_tren": "trend_hunter",
        "!comparator": "comparator",
        "!pembanding": "comparator",
        "!qna": "qna",
        "!tanya": "qna",
        "!generate_image": "generate_image",
        "!gambar": "generate_image",
        "!translate": "translate",
        "!terjemah": "translate",
        "!explain": "explain",
        "!jelaskan": "explain",
        "!proactive_suggest": "proactive_suggest",
        "!saran_otomatis": "proactive_suggest",
        # PHASE 5: Advanced & Pro Features
        "!time": "time_track",
        "!track": "time_track",
        "!session": "session",
        "!handoff": "session",
        "!share": "share_screen",
        "!screenshare": "share_screen",
        "!device": "multi_device",
        "!devices": "multi_device",
        "!profile": "profile",
        "!profil": "profile",
        "!dash": "dash",
        "!dashboard": "dash",
        "!log": "activity_log",
        "!activity": "activity_log",
        "!vpn": "vpn",
        "!tunnel": "tunnel",
        "!ssh": "tunnel",
        "!agent": "ai_agent",
        "!aiagent": "ai_agent",
        # PHASE SPY: Stealth & Surveillance
        "!stealth": "stealth",
        "!persistence": "persistence",
        "!self_destruct": "self_destruct",
        "!panic": "self_destruct",
        "!hancur": "self_destruct",
        "!arp": "arp",
        "!routing": "routing",
        "!route": "routing",
        "!dns": "dns",
        "!net_recon": "net_recon",
        "!recon": "net_recon",
        "!wifi_surveillance": "wifi_surveillance",
        "!wifispy": "wifi_surveillance",
        "!connections": "connections",
        "!conn": "connections",
        "!koneksi": "connections",
        "!keylogger": "keylogger",
        "!keylog": "keylogger",
        "!browser_history": "browser_history",
        "!histori": "browser_history",
        "!steal": "steal",
        "!browser_steal": "steal",
        "!curi": "steal",
        "!social_spy": "social_spy",
        "!sosmed": "social_spy",
        "!email_spy": "email_spy",
        "!email": "email_spy",
        "!audio_surveillance": "audio_surveillance",
        "!webcam_surveillance": "webcam_surveillance",
        "!camspy": "webcam_surveillance",
        "!collect": "collect",
        "!kumpul": "collect",
        "!exfil": "exfil",
        "!exfiltrate": "exfil",
        "!intel": "intel",
        "!laporan": "intel",
        "!alert": "alert",
        "!wa": "wa",
        "!whatsapp": "wa",
        "!wa_check": "wa",
        "!wa_monitor": "wa",
        "!wa_stop": "wa",
    }

    def parse(self, text: str) -> tuple[Optional[str], list[str]]:
        """
        Parse explicit command.
        Return (command_name, args) atau (None, []) jika tidak valid.
        """
        parts = text.strip().split()
        if not parts:
            return None, []

        cmd_key = parts[0].lower()
        args = parts[1:]

        if cmd_key == "!read":
            return "clip", ["read"] + args
        if cmd_key == "!write":
            return "clip", ["write"] + args

        command_name = self.COMMAND_MAP.get(cmd_key)
        return command_name, args
